baseURL = '"https://Taha2053.github.io/ATKlog/"'
languageCode = 'en-us'
title = 'ATK`log'
theme= 'paper'
enableInlineShortcodes = true


#disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[params]
  # color style
  color = 'gray'                           # linen, wheat, gray, light

  # header social icons
  #twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'Taha2053'                 # github.com/YOUR_GITHUB_ID
  #instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'taha-kh-841237261'             # linkedin.com/in/YOUR_LINKEDIN_ID
  email = 'at2053k@gmail.com'
  #rss = true                                # show rss icon

  # home page profile
  avatar = 'https://0.gravatar.com/userimage/220325386/bbf4c01caf23a6a46eaebcb1337d6df5?size=256'                 # gravatar email or image url
  name = 'Taha Kh'
  bio = 'a description '


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # giscus
[params.giscus]
  repo = 'YOUR_GISCUS_REPO'                 # see https://giscus.app for more details
  repoId = 'YOUR_GISCUS_REPO_ID'
  category = 'YOUR__GISCUS_CATEGORY'
  categoryId = 'YOUR_GISCUS_CATEGORY_ID'
  mapping = 'pathname'
  theme = 'light'
  lang = 'zh-CN'

  # needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true


[menu]



  [[menu.main]]
    identifier = "about-me"
    name = "About me"
    url = "/about-me/"
    weight = 20

  [[menu.main]]
    identifier = "blog"
    name ="Blog"
    url="/blog/"
    weight =30

  [[menu.main]]
    identidier="projects"
    name ="Projects"
    url="/projects/"
    weight =50

[taxonomies]
category = "categories"
tag = "tags"
series = "series"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true